name: Release

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
    - name: Test
      run: go test -v ./...
    - name: Lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: latest

  release:
    needs: test
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
    
    - name: Build binaries
      run: |
        GOOS=linux GOARCH=amd64 go build -o azr-linux-amd64 ./cmd/azr
        GOOS=linux GOARCH=arm64 go build -o azr-linux-arm64 ./cmd/azr
        GOOS=darwin GOARCH=amd64 go build -o azr-darwin-amd64 ./cmd/azr
        GOOS=darwin GOARCH=arm64 go build -o azr-darwin-arm64 ./cmd/azr
        GOOS=windows GOARCH=amd64 go build -o azr-windows-amd64.exe ./cmd/azr
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          azr-linux-amd64
          azr-linux-arm64
          azr-darwin-amd64
          azr-darwin-arm64
          azr-windows-amd64.exe
        draft: false
        prerelease: false
        generate_release_notes: true 